#!/bin/bash

#----------------------------------------------------------------------------
# environment & site config, if any
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
[ -f ${SCRIPTDIR}/config_env.sh ] && . ${SCRIPTDIR}/config_env.sh
#----------------------------------------------------------------------------

launch_cf_PBS_script="${SCRIPTDIR}/launch_cf.pbs"

[ -f ${launch_cf_PBS_script} ] || { echo "ERROR: cannot locate ${launch_cf_PBS_script}"; exit 1; }

#------------------------------------------------------------------
# bash function to count lines not beginning with "#" from a text file
count_non_comment_lines ()
{
    i=0
    while read line; do
	# skip comment lines beginning with "#"
	[[ ${line:0:1} == "#" ]] && continue || i=$((i + 1))
    done < "${1}"
    echo ${i}
    return 0
}


#------------------------------------------------------------------
usage ()
{
    echo "FIXME!!"
}

#------------------------------------------------------------------
parse_args ()
{
    while [ ${#} -gt 0 ] ; do
        # check the first argument
        case ${1} in

            "-h"|"--help")
                usage
                shift
                exit 1
                ;;

            *)
                if [ -f ${1} ]; then
                    command_file="${1}"
                else
                    args_for_pbs="${args_for_pbs} ${1}"
                fi
                shift # past argument
                ;;
        esac
    done

    return
}

#------------------------------------------------------------------
# var defaults.
# FIXME: handle some command line args
unset args_for_pbs
command_file="./cmdfile"

case "${NCAR_HOST}" in
    "derecho")
        ppn=128
        memlimit="235G"
        defqueue="main"
        ;;
    "casper")
        # use less than full nodes on Casper.
        ppn=8
        memlimit="80G"
        defqueue="casper"
        ;;
    "cheyenne")
        ppn=36
        memlimit="50G"
        defqueue="regular"
        ;;
    *)
        echo "ERROR: Unrecognized NCAR_HOST=${NCAR_HOST}"
        exit 1
esac

parse_args $@

#------------------------------------------------------------------
# error checking
[ -r ${command_file} ] || { echo "Cannot locate requested command file: ${command_file}"; exit 1; }

#------------------------------------------------------------------
# main execution follows...
nsteps=$(count_non_comment_lines ${command_file})

echo "Found nsteps=${nsteps} in ${command_file}"

#------------------------------------------------------------------
echo "Running ${ppn} steps / node on NCAR resource ${NCAR_HOST}"

njobs=$(( ${nsteps} / ${ppn} ))
ss="1:ncpus=${ppn}:mpiprocs=${ppn}:mem=${memlimit}"


# FIXME:  passes on all command arguments, if any, to qsub.
set -x
qsub -v command_file="${command_file}" \
     -q ${defqueue} -J 0-${njobs} -l select=${ss} \
     ${args_for_pbs} \
     ${launch_cf_PBS_script}
