FROM alpine:latest

COPY extras/speak.sh /opt/container/speak.sh
COPY extras/list_glade_filesystems.sh /opt/container/list_glade_filesystems.sh

RUN chmod +x /opt/container/*.sh \
    && mkdir -p /glade/u/home /glade/work /glade/campaign /glade/derecho/scratch /random/path

ENV CONTAINER_VAR="bar" \
    TOGGLE_VAR="set_from_INSIDE"
